name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Clean
        run: go clean -modcache -v

      - name: Build binary
        run: |
          mkdir -p ./publish
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -o ./publish/myapp-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} ./cmd/main/repobackup.go

      - name: Upload binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
