name: Test and Lint
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
          skip-cache: true
          args: --config=.golangci.yml

      - name: Clean
        run: go clean -modcache -v

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Test
        run: go test ./...

      - name: Clean
        run: go clean -modcache -v
